import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { writeRootJson } from "../config/root-json.js";
import { type InitAnswers, answersToRootJson } from "../init/answers.js";
import type { StructureizeResult } from "../init/structureizer.js";
import { assertNoNodeProjectFiles } from "./language-agnostic.js";

async function write(targetDir: string, rel: string, content: string, files: string[]) {
  const full = path.join(targetDir, rel);
  await mkdir(path.dirname(full), { recursive: true });
  await writeFile(full, content, "utf8");
  files.push(rel);
}

/** Pure Python FastAPI project — zero Node project files. */
export async function structureizeFastapi(options: {
  targetDir: string;
  answers: InitAnswers;
}): Promise<StructureizeResult> {
  const { targetDir, answers } = options;
  const filesWritten: string[] = [];
  const name = answers.projectName;

  await write(
    targetDir,
    "pyproject.toml",
    `[project]
name = "${name}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.115.0",
  "uvicorn[standard]>=0.32.0",
${answers.orm === "sqlalchemy" ? '  "sqlalchemy>=2.0.0",\n  "greenlet>=3.0.0",\n' : ""}]
`,
    filesWritten,
  );

  await write(
    targetDir,
    "requirements.txt",
    `fastapi>=0.115.0
uvicorn[standard]>=0.32.0
${answers.orm === "sqlalchemy" ? "sqlalchemy>=2.0.0\ngreenlet>=3.0.0\n" : ""}`,
    filesWritten,
  );

  await write(
    targetDir,
    "app/main.py",
    `from fastapi import FastAPI

app = FastAPI(title="${name}")

@app.get("/health")
def health():
    return {"ok": True}
`,
    filesWritten,
  );

  await write(
    targetDir,
    "README.md",
    `# ${name}

Generated by Root (FastAPI). No Node.js project files.

\`\`\`bash
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
uvicorn app.main:app --reload
\`\`\`
`,
    filesWritten,
  );

  const rootJson = answersToRootJson({
    ...answers,
    language: "python",
    framework: "fastapi",
    validation: "pydantic",
    testing: "pytest",
    packageManager: answers.packageManager === "uv" ? "uv" : "pip",
  });
  // Python projects use empty Node-style aliases placeholders for doctor compatibility
  rootJson.aliases = {
    routes: "app",
    controllers: "app",
    services: "app",
    middleware: "app",
    schema: "app/main.py",
    server: "app/main.py",
    db: "app",
  };
  const rootJsonPath = await writeRootJson(targetDir, rootJson);
  filesWritten.push("root.json");

  await assertNoNodeProjectFiles(targetDir);
  return { filesWritten, rootJsonPath };
}

/** Pure Python Flask project — zero Node project files. */
export async function structureizeFlask(options: {
  targetDir: string;
  answers: InitAnswers;
}): Promise<StructureizeResult> {
  const { targetDir, answers } = options;
  const filesWritten: string[] = [];
  const name = answers.projectName;

  await write(
    targetDir,
    "requirements.txt",
    `flask>=3.0.0
${answers.orm === "sqlalchemy" ? "sqlalchemy>=2.0.0\n" : ""}`,
    filesWritten,
  );

  await write(
    targetDir,
    "app.py",
    `from flask import Flask, jsonify

app = Flask(__name__)

@app.get("/health")
def health():
    return jsonify(ok=True)

if __name__ == "__main__":
    app.run(debug=True)
`,
    filesWritten,
  );

  await write(
    targetDir,
    "README.md",
    `# ${name}

Generated by Root (Flask). No Node.js project files.

\`\`\`bash
python -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
flask --app app run --debug
\`\`\`
`,
    filesWritten,
  );

  const rootJson = answersToRootJson({
    ...answers,
    language: "python",
    framework: "flask",
    validation: "none",
    testing: "pytest",
    packageManager: "pip",
  });
  rootJson.aliases = {
    routes: ".",
    controllers: ".",
    services: ".",
    middleware: ".",
    schema: "app.py",
    server: "app.py",
    db: ".",
  };
  const rootJsonPath = await writeRootJson(targetDir, rootJson);
  filesWritten.push("root.json");
  await assertNoNodeProjectFiles(targetDir);
  return { filesWritten, rootJsonPath };
}

/** Pure Go net/http project — zero Node project files. */
export async function structureizeGoHttp(options: {
  targetDir: string;
  answers: InitAnswers;
}): Promise<StructureizeResult> {
  const { targetDir, answers } = options;
  const filesWritten: string[] = [];
  const name = answers.projectName;
  const module = `example.com/${name}`;

  await write(
    targetDir,
    "go.mod",
    `module ${module}

go 1.22
${answers.orm === "gorm" ? "\nrequire gorm.io/gorm v1.25.12\n" : ""}`,
    filesWritten,
  );

  await write(
    targetDir,
    "main.go",
    `package main

import (
  "encoding/json"
  "log"
  "net/http"
)

func main() {
  mux := http.NewServeMux()
  mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
    w.Header().Set("Content-Type", "application/json")
    _ = json.NewEncoder(w).Encode(map[string]bool{"ok": true})
  })
  log.Println("listening on :8080")
  log.Fatal(http.ListenAndServe(":8080", mux))
}
`,
    filesWritten,
  );

  await write(
    targetDir,
    "README.md",
    `# ${name}

Generated by Root (Go net/http). No Node.js project files.

\`\`\`bash
go mod tidy
go run .
\`\`\`
`,
    filesWritten,
  );

  const rootJson = answersToRootJson({
    ...answers,
    language: "go",
    framework: "go-http",
    validation: "none",
    testing: "none",
    packageManager: "go-mod",
  });
  rootJson.aliases = {
    routes: ".",
    controllers: ".",
    services: ".",
    middleware: ".",
    schema: "main.go",
    server: "main.go",
    db: ".",
  };
  const rootJsonPath = await writeRootJson(targetDir, rootJson);
  filesWritten.push("root.json");
  await assertNoNodeProjectFiles(targetDir);
  return { filesWritten, rootJsonPath };
}
