export const SERVER_FIXTURE = `import cors from "cors";
import express, { type Express } from "express";
import helmet from "helmet";
import { errorHandler } from "./middleware/errorHandler.js";
import { requestLogger } from "./middleware/logger.js";
import { healthRouter } from "./routes/health.routes.js";
import { apiRouter } from "./routes/index.js";

export function createServer(): Express {
  const app = express();

  app.use(helmet());
  app.use(cors());
  app.use(express.json());
  app.use(requestLogger);

  app.use("/health", healthRouter);
  app.use("/api", apiRouter);

  // [ROOT-INJECT:ROUTES]

  app.use(errorHandler);

  return app;
}
`;

export const SCHEMA_FIXTURE = `// schema.ts — Auto-generated by Root CLI. Do not edit section banners.
import { z } from "zod";

// ─── Auth Schemas ─────────────────────────────────────────────────────────────

// ─── Resource Schemas ─────────────────────────────────────────────────────────

// ─── Exports ──────────────────────────────────────────────────────────────────
export {};
`;
