import type { Operation } from "../../engine/operations.js";
import { isTypeScript, sourceExtension } from "../../providers/language.js";
import { resolveResourceNames } from "../codegen/resource-files.js";
import { toPascalCase } from "../types.js";
import type { Recipe } from "../types.js";

/** Atomic controller stub (warn when no matching route module). */
export const controllerRecipe: Recipe = {
  id: "controller",
  description: "Controller stub",
  registryDependencies: [],
  plan(ctx) {
    const resourceName = ctx.resourceName;
    if (!resourceName) {
      throw new Error("controller recipe requires resourceName");
    }

    const names = resolveResourceNames(resourceName);
    if (ctx.graph.config.modules[names.slug]) {
      return [];
    }

    const pascal = toPascalCase(names.slug);
    const controllersDir = ctx.graph.config.aliases.controllers;
    const ext = sourceExtension(ctx.graph.config);
    const addedAt = ctx.addedAt ?? "1970-01-01T00:00:00.000Z";

    const content = isTypeScript(ctx.graph.config)
      ? `import type { NextFunction, Request, Response } from "express";

/**
 * ${pascal} controller — generated by Root \`add resource\`.
 * Wire handlers into a route file to expose HTTP endpoints.
 */

export async function list${pascal}(_req: Request, res: Response, next: NextFunction) {
  try {
    res.status(200).json({ success: true, data: [] });
  } catch (error) {
    next(error);
  }
}

export async function get${pascal}ById(req: Request, res: Response, next: NextFunction) {
  try {
    res.status(200).json({ success: true, data: { id: req.params.id } });
  } catch (error) {
    next(error);
  }
}

export async function create${pascal}(req: Request, res: Response, next: NextFunction) {
  try {
    res.status(201).json({ success: true, data: req.body });
  } catch (error) {
    next(error);
  }
}
`
      : `/**
 * ${pascal} controller — generated by Root \`add resource\`.
 * Wire handlers into a route file to expose HTTP endpoints.
 */

export async function list${pascal}(_req, res, next) {
  try {
    res.status(200).json({ success: true, data: [] });
  } catch (error) {
    next(error);
  }
}

export async function get${pascal}ById(req, res, next) {
  try {
    res.status(200).json({ success: true, data: { id: req.params.id } });
  } catch (error) {
    next(error);
  }
}

export async function create${pascal}(req, res, next) {
  try {
    res.status(201).json({ success: true, data: req.body });
  } catch (error) {
    next(error);
  }
}
`;

    const ops: Operation[] = [
      {
        type: "createFile",
        path: `${controllersDir}/${names.slug}.controller.${ext}`,
        content,
      },
      {
        type: "updateManifest",
        moduleName: names.slug,
        entry: { type: "controller", addedAt },
      },
    ];

    return ops;
  },
};
