import type { Operation } from "../../engine/operations.js";
import { resolveResourceNames } from "../codegen/resource-files.js";
import { toCamelCase, toPascalCase } from "../types.js";
import type { Recipe } from "../types.js";

/** Atomic Express middleware stub. */
export const middlewareRecipe: Recipe = {
  id: "middleware",
  description: "Express middleware stub",
  registryDependencies: [],
  plan(ctx) {
    const resourceName = ctx.resourceName;
    if (!resourceName) {
      throw new Error("middleware recipe requires resourceName");
    }

    const names = resolveResourceNames(resourceName);
    if (ctx.graph.config.modules[names.slug]) {
      return [];
    }

    const pascal = toPascalCase(names.slug);
    const camel = toCamelCase(names.slug);
    const mwDir = ctx.graph.config.aliases.middleware;
    const addedAt = ctx.addedAt ?? "1970-01-01T00:00:00.000Z";
    const exportName = camel === "auth" ? "customAuth" : camel;

    const ops: Operation[] = [
      {
        type: "createFile",
        path: `${mwDir}/${names.slug}.ts`,
        content: `import type { NextFunction, Request, Response } from "express";

/**
 * ${pascal} middleware — generated by Root \`add middleware\`.
 * Mount on a router: router.use(${exportName})
 */
export function ${exportName}(req: Request, res: Response, next: NextFunction): void {
  void req;
  void res;
  next();
}
`,
      },
      {
        type: "updateManifest",
        moduleName: names.slug,
        entry: { type: "middleware", addedAt },
      },
    ];

    return ops;
  },
};
