import type { Recipe } from "../types.js";

/** Ensures schema.ts exists with Root section banners (stub — create only if missing). */
export const schemaRecipe: Recipe = {
  id: "schema",
  description: "Zod schema registry file with auth/resource/export banners",
  registryDependencies: [],
  plan(ctx) {
    if (ctx.graph.probe.hasSchemaFile) {
      return [];
    }

    const schemaRel = ctx.graph.config.aliases.schema;
    return [
      {
        type: "createFile",
        path: schemaRel,
        content: `// schema.ts — Auto-generated by Root CLI. Do not edit section banners.
import { z } from "zod";

// ─── Auth Schemas ─────────────────────────────────────────────────────────────

// ─── Resource Schemas ─────────────────────────────────────────────────────────

// ─── Exports ──────────────────────────────────────────────────────────────────
export {};
`,
      },
      {
        type: "ensureDependency",
        name: "zod",
        version: "^3.24.2",
      },
    ];
  },
};
