import type { Operation } from "../../engine/operations.js";
import { isTypeScript, sourceExtension } from "../../providers/language.js";
import { resolveResourceNames } from "../codegen/resource-files.js";
import { toPascalCase } from "../types.js";
import type { Recipe } from "../types.js";

/** Atomic service stub (not mounted to HTTP by itself). */
export const serviceRecipe: Recipe = {
  id: "service",
  description: "Service layer stub",
  registryDependencies: [],
  plan(ctx) {
    const resourceName = ctx.resourceName;
    if (!resourceName) {
      throw new Error("service recipe requires resourceName");
    }

    const names = resolveResourceNames(resourceName);
    if (ctx.graph.config.modules[names.slug]) {
      return [];
    }

    const pascal = toPascalCase(names.slug);
    const servicesDir = ctx.graph.config.aliases.services;
    const ext = sourceExtension(ctx.graph.config);
    const addedAt = ctx.addedAt ?? "1970-01-01T00:00:00.000Z";

    const content = isTypeScript(ctx.graph.config)
      ? `/**
 * ${pascal} service — generated by Root \`add service\`.
 * Wire this into a controller/route to expose HTTP endpoints.
 */

export async function list${pascal}() {
  return [] as const;
}

export async function get${pascal}ById(id: string) {
  void id;
  return null;
}

export async function create${pascal}(input: Record<string, unknown>) {
  return { id: crypto.randomUUID(), ...input };
}
`
      : `/**
 * ${pascal} service — generated by Root \`add service\`.
 * Wire this into a controller/route to expose HTTP endpoints.
 */

export async function list${pascal}() {
  return [];
}

export async function get${pascal}ById(id) {
  void id;
  return null;
}

export async function create${pascal}(input) {
  return { id: crypto.randomUUID(), ...input };
}
`;

    const ops: Operation[] = [
      {
        type: "createFile",
        path: `${servicesDir}/${names.slug}.service.${ext}`,
        content,
      },
      {
        type: "updateManifest",
        moduleName: names.slug,
        entry: { type: "service", addedAt },
      },
    ];

    return ops;
  },
};
